spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#   TODO:rabbitmq:
#   TODO:redis:
#   TODO:cache:
server:
  port: 8081
  compression:
    enabled: true
# TODO:fastdfs: